In [10]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter
import seaborn as sns
from matplotlib.colors import ListedColormap
import warnings
warnings.filterwarnings('ignore')
from pandas import ExcelWriter
from pandas import ExcelFile
from datetime import datetime

In [26]:
#Reading the login file
df_login = pd.read_excel('/Users/venkateshiyersubramanian/Downloads/convertcsv.xlsx')
df_login.head()

            login_date      Time       Date
0  1970-01-01 20:13:18  20:13:18 1970-01-01
1  1970-01-01 20:16:10  20:16:10 1970-01-01
2  1970-01-01 20:16:37  20:16:37 1970-01-01
3  1970-01-01 20:16:36  20:16:36 1970-01-01
4  1970-01-01 20:26:21  20:26:21 1970-01-01

In [27]:
#Resampling for creation of 15 min interval:
df_login1 = pd.DataFrame(data=df_login)

In [29]:
df_login1.resample('15min').sum()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

In [9]:
# Downloading and reading the csv file
data = pd.read_csv("/Users/venkateshiyersubramanian/Documents/GitHub/Springboard/ultimate_challenge/Ultimate.csv")
data.head(10)

,city,trips_in_first_30_days,signup_date,avg_rating_of_driver,avg_surge,last_trip_date,phone,surge_pct,ultimate_black_user,weekday_pct,avg_dist,avg_rating_by_driver
0,King's Landing,4,2014-01-25,4.7,1.10,2014-06-17,iPhone,15.4,True,46.2,3.67,5.0
1,Astapor,0,2014-01-29,5.0,1.00,2014-05-05,Android,0.0,False,50.0,8.26,5.0
2,Astapor,3,2014-01-06,4.3,1.00,2014-01-07,iPhone,0.0,False,100.0,0.77,5.0
3,King's Landing,9,2014-01-10,4.6,1.14,2014-06-29,iPhone,20.0,True,80.0,2.36,4.9
4,Winterfell,14,2014-01-27,4.4,1.19,2014-03-15,Android,11.8,False,82.4,3.13,4.9
5,Winterfell,2,2014-01-09,3.5,1.00,2014-06-06,iPhone,0.0,True,100.0,10.56,5.0
6,Astapor,1,2014-01-24,NaN,1.00,2014-01-25,Android,0.0,False,100.0,3.95,4.0
7,Winterfell,2,2014-01-28,5.0,1.00,2014-01-29,iPhone,0.0,False,100.0,2.04,5.0
8,Winterfell,2,2014-01-21,4.5,1.00,2014-02-01,Android,0.0,False,100.0,4.36,5.0
9,Winterfell,1,2014-01-03,NaN,1.00,2014-01-05,Android,0.0,False,0.0,2.37,5.0

In [2]:
conda install -c conda-forge category_encoders

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - category_encoders


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    category_encoders-2.1.0    |             py_0          48 KB  conda-forge
    conda-4.8.0                |           py37_1         3.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.0 MB

The following NEW packages will be INSTALLED:

  category_encoders  conda-forge/noarch::category_encoders-2.1.0-py_0

The following packages will be UPDATED:

  conda                      pkgs/main::conda-4.7.12-py37_0 --> conda-forge::conda-4.8.0-py37_1



Downloading and Extracting Packages
conda-4.8.0          | 3.0 MB    | ##################################### | 100%
category_encoders-2. | 48 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: \ WARNING conda.core.path_actions:verify(963): Unable to create environments file. Path not writable.
  environment location: /Users/venkateshiyersubramanian/.conda/environments.txt

done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [6]:
data.shape

(50000, 12)

In [10]:
#Converting in to a dataframe we see that the most missing values are in rating of a driver, phone and
#rating by driver
df = pd.DataFrame(data)
len(df) - df.count()

city                         0
trips_in_first_30_days       0
signup_date                  0
avg_rating_of_driver      8122
avg_surge                    0
last_trip_date               0
phone                      396
surge_pct                    0
ultimate_black_user          0
weekday_pct                  0
avg_dist                     0
avg_rating_by_driver       201
dtype: int64